name: "检查"

on: [push, pull_request, merge_group, workflow_dispatch, workflow_call]

concurrency:
  group: "check"
  cancel-in-progress: false

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  fomat-check:
    runs-on: ubuntu-latest
    name: "多语言格式检查"
    steps:
      - name: 检出仓库
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: AutoCorrect
        uses: huacnlee/autocorrect-action@v2

      - name: Report ReviewDog
        if: failure()
        uses: huacnlee/autocorrect-action@v2
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          reviewdog: true

  book-run-test:
    runs-on: ubuntu-latest
    name: "框架静态测试"
    steps:
      - name: 检出仓库
        uses: actions/checkout@v4

      - name: 配置 mdBook
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: "0.5.2"
          # mdbook-version: 'latest'

      - name: 初始化 Pages
        id: pages
        if: github.repository != 'haytham-ai/public-docs'
        continue-on-error: true # 避免用户仓库未开启 GitHub Pages 时报错
        uses: actions/configure-pages@v5

      - name: 构建测试
        run: mdbook -V && mdbook build && mdbook test

      - name: 上传待部署文件
        if: github.repository != 'haytham-ai/public-docs'
        continue-on-error: true # 避免用户仓库未开启 GitHub Pages 时报错
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./book

  test-deploy:
    name: "部署测试"
    environment:
      name: "GitHub Pages"
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: book-run-test
    steps:
      - name: 部署至 GitHub Pages
        id: deployment
        if: github.repository != 'haytham-ai/public-docs'
        continue-on-error: true # 避免用户仓库未开启 GitHub Pages 时报错
        uses: actions/deploy-pages@v4
